### ISSUE TITLE
Missing 'meters' from 'nerfstudio.utils'

### ISSUE THREAD

**Issue by rikkazz** [VISION-SJTU/Lightning-NeRF#1]
At lightning_nerf/model.py line 29
from nerfstudio.utils import colormaps, meters, misc
can not find 'meters' in any version of nerfstudio
v0.2.2: https://github.com/nerfstudio-project/nerfstudio/tree/main/nerfstudio/utils

**Comment by rikkazz** [comment]
from nerfstudio.utils import colormaps, meters, misc

**Comment by XJay18** [comment]
Thank you for mentioning the issue. It turns out I have edited some files in the NeRFStudio project locally. I have reorganized our code to include those implementations. Please pull the updated version (commit `a6f5422`) and check it again. Sorry for the inconvenience.
