### ISSUE TITLE
Can you provide some guidance on preparing the custom dataset?

### ISSUE THREAD

**Issue by Yellowshuohahaha** [VISION-SJTU/Lightning-NeRF#5]

**Comment by XJay18** [comment]
Hi, basically, you need to:
1. Prepare a dataset with images and camera information;
2. Obtain corresponding pointcloud data from lidar sensors;
3. Preprocess pointcloud data (e.g., denoising and downsampling);
4. Visualize 3D pointcloud along with cameras, and define the foreground region to cover the view frustums;
5. Implement a custom dataparser in NeRFStudio, which reads images, camera information, and pointcloud data.

You may refer to [this link](https://drive.google.com/file/d/1FvDp_AyugRIMvIzrN7_JaEdq3eMVkjb6/view?usp=sharing), where I uploaded the code for preprocessing Argoverse2.

**Comment by Yellowshuohahaha** [comment]
@XJay18 Thank you! It is helpful for me!
