### ISSUE TITLE
Renderer Output

### ISSUE THREAD

**Issue by atharvahude** [VISION-SJTU/Lightning-NeRF#6]
Hello, I've managed to train the lighting nerf on one of the sequences. However, I'm uncertain if the output visualized in Nerf Studio is what's expected. Could you please confirm and share some screenshots of the output for refrence?

My Screenshots: 
![WhatsApp Image 2024-04-13 at 9 20 55 PM](https://github.com/VISION-SJTU/Lightning-NeRF/assets/43880398/6ece093d-1d84-4ed6-b16e-88045b609f77)
![WhatsApp Image 2024-04-13 at 9 20 41 PM](https://github.com/VISION-SJTU/Lightning-NeRF/assets/43880398/ed44798f-2bad-4ee2-a366-496d452de111)

**Comment by XJay18** [comment]
Hi, I think you're on the right track. However, you should set `Output Render` to `rgb` in the right panel to see the rendered images. Once the training progress is finished, you can run the command
```{bash}
ns-viewer --load-config {path/to/config.yml}
```
to reactivate the viewer to see the rendered results.

**Comment by XJay18** [comment]
Close due to inactivation. Please feel free to reopen this issue if you still have related problems.
